#compiled from: https://www.webopedia.com/reference/twitter-dictionary-guide/
abbrevations = {
    "i don't know": "idk",
    "right now": "rn",
    "oh my god": "omg",  
    "i don't care": "idc",
    "laugh out loud": "lol", 
    "brother":"bro", 
    "direct message": "dm",
    "what the fuck": "wtf",
    "laughing my ass off": "lmao",
    "sorry": "sry", 
    "very": "v",
    "with": "w",
    "nevermind": "nvm",
    "rolling on the floor laughing": "rofl",
    "let me know": "lmk",
    "i love you": "ily",
    "you only live once": "yolo",
    "laughing my fucking ass off": "lmfao",
    "i know right": "ikr",
    "of course": "ofc",
    "you": "u",
    "too": "2",
    "to": "2",
    "are": "r",
    "about": "abt",
    "to be honest": "tbh",
    "throwback thursday": "tbt",
    "tweet me back": "tmb",
    "thanks for the follow": "tftf",
    "shaking my head": "smh",
    "please retweet": "prt",
    "retweet": "rt",
    "note to self": "nts",
    "more to follow": "mtf",
    "modified retweet": "mrt",
    "okay": "kk",
    "in my opinion": "imo",
    "in case you missed it": "icymi",
    "i see": "ic",
    "hat tip": "ht",
    "for the win": "ftw",
    "for the loss": "ftl",
    "fear of missing out": "fomo",
    "fabulous": "fab",
    "email": "eml",
    "email address": "ema",
    "details": "deets",
    "create": "cr8",
    "click": "clk",
    "could": "cld",
    "check": "chk",
    "by the way": "btw",
    "best regards": "br",
    "background": "bgd",
    "bye for now": "bfn",
    "before": "b4",
    "because": "bc"
}