#compiled from: https://www.webopedia.com/reference/twitter-dictionary-guide/
abbrevations = {
    "i don't know": "idk",
    "right now": "rn",
    "oh my god": "omg",  
    "i don't care": "idc",
    "laugh out loud": "lol", 
    "brother":"bro", 
    "direct message": "dm",
    "what the fuck": "wtf",
    "laughing my ass off": "lmao",
    "sorry": "sry", 
    "very": "v",
    "with": "w",
    "nevermind": "nvm",
    "rolling on the floor laughing": "rofl",
    "let me know": "lmk",
    "i love you": "ily",
    "you only live once": "yolo",
    "laughing my fucking ass off": "lmfao",
    "i know right": "ikr",
    "of course": "ofc",
    "you": "u",
    "are": "r",
    "about": "abt",
    "to be honest": "tbh",
    "throwback thursday": "tbt",
    "shaking my head": "smh",
    "retweet": "rt",
    "okay": "kk",
    "in my opinion": "imo",
    "i see": "ic",
    "hat tip": "ht",
    "for the win": "ftw",
    "fabulous": "fab",
    "email address": "ema",
    "details": "deets",
    "could": "cld",
    "by the way": "btw",
    "best regards": "br",
    "before": "b4",
    "because": "bc"
}